codename1.android.keystore=
codename1.android.keystoreAlias=
codename1.android.keystorePassword=
codename1.arg.and.themeMode=modern
codename1.arg.android.manifest.queries=<package android\:name\="com.ichi2.anki"/><package android\:name\="com.duolingo"/><package android\:name\="com.languagedrops.drops.international"/><package android\:name\="air.com.rosettastone.mobile.CoursePlayer"/><package android\:name\="com.rosettastone.sapphire"/><package android\:name\="ai.talkpal"/><package android\:name\="com.quizlet.quizletandroid"/>
codename1.arg.android.proguardKeep=-keep class net.informaticalibera.streakapp.native_.** { *; }
codename1.arg.android.xpermissions=<uses-permission android\:name\="android.permission.PACKAGE_USAGE_STATS"/>
codename1.arg.ios.newStorageLocation=true
codename1.arg.ios.themeMode=modern
codename1.arg.java.version=17
codename1.arg.nativeTheme=modern
codename1.cssTheme=true
codename1.description=StreakApp
codename1.displayName=StreakApp
codename1.icon=icon.png
codename1.ios.appid=Q5GHSKAL2F.net.informaticalibera.streakapp
codename1.ios.certificate=
codename1.ios.certificatePassword=
codename1.ios.debug.certificate=
codename1.ios.debug.certificatePassword=
codename1.ios.debug.provision=
codename1.ios.provision=
codename1.ios.release.certificate=
codename1.ios.release.certificatePassword=
codename1.ios.release.provision=
codename1.kotlin=false
codename1.mainName=StreakApp
codename1.packageName=net.informaticalibera.streakapp
codename1.secondaryTitle=Study Streak Tracker
codename1.vendor=Francesco Galgani
codename1.version=1.0
